scrape_configs:
  - job_name: 'resource-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          application: 'Resource Service Metrics'
  - job_name: 'resource-processor-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - host.docker.internal:8081
        labels:
          application: 'Resource Processor Service Metrics'
  - job_name: 'songs-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - host.docker.internal:8082
        - host.docker.internal:8083
        - host.docker.internal:8084
        - host.docker.internal:8085
        labels:
          application: 'Songs App Metrics'
  - job_name: 'storage-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8086']
        labels:
          application: 'Storage Service Metrics'